blank_issues_enabled: true
contact_links:
  - name: Arkham Core Security Policy
    url: https://github.com/arkham/arkham/blob/master/SECURITY.md
    about: View security policy
  - name: Arkham Core Developers
    url: https://arkhamcore.org
    about: Arkham Core homepage
